################################################################################
# Example Lazy.jl parameter file, May 2025, v1.0.3
################################################################################

[io]
    # Path to the input catalog file, in fits format
    input_catalog = '/path/to/catalog/file.fits' 

    # Format for missing data in the input catalog (e.g. 'nan' or -99) 
    missing_data_format = 'nan' 

    # Name of the output fits file 
    output_file = '/path/to/lazy_results.fits'
    
    # Whether to output the redshift probability distribution for each object
    # If true, outputs to output_file in extension "PZ" 
    output_pz = true 
    
    # Whether to output the template set used, including IGM attenuation 
    # This is needed in order to reconstruct the best-fit SEDs later
    # If true, outputs to output_file in extension "TEMPL" 
    output_templates = true 

[fitting]
    # Template set to use for fitting. This should correspond to an entry in the
    # "template_directory.toml" file. Use `lazy list-templates` to see the 
    # available template sets. Alternatively, you can specify a custom template
    # set by providing a list of template files.
    
    template_set = 'sfhz' 
    # template_set = [
    #     'sfhz/corr_sfhz_13_bin3_av0.50.fits', 
    #     'sfhz/corr_sfhz_13_bin3_av0.01.fits', 
    #     ...
    # ]

    # Template error function to use (currently only 'template_error' supported)
    template_error = 'template_error' 

    # Scale factor for the template error function
    template_error_scale = 0.2 

    # IGM attenuation model to use (currently only 'inoue14' is supported)
    igm_model = 'inoue14'
    
    # Minimum number of valid (non-nan, snr>2) photometric points to run the fit
    nphot_min = 2 

    # Systematic error to add in quadrature to the photometric errors
    sys_err = 0.05

    # Redshift grid to use for fitting
    z_min = 0.0
    z_max = 20.0
    z_step = 0.01

[translate]
    # Tells the code which columns in the input catalog to use for the fluxes 
    # and errors in each band.The keys are the filter names, which correspond to
    # entries in the "filter_directory.toml" file. Use `lazy list-filters` to 
    # see the available filters. The entires should correspond to column names
    # in the input catalog

    f606w = {flux = 'f_f606w', error = 'e_f606w'}
    f814w = {flux = 'f_f814w', error = 'e_f814w'}
    f090w = {flux = 'f_f090w', error = 'e_f090w'}
    f115w = {flux = 'f_f115w', error = 'e_f115w'}
    f150w = {flux = 'f_f150w', error = 'e_f150w'}
    f200w = {flux = 'f_f200w', error = 'e_f200w'}
    f277w = {flux = 'f_f277w', error = 'e_f277w'}
    f356w = {flux = 'f_f356w', error = 'e_f356w'}
    f410m = {flux = 'f_f410m', error = 'e_f410m'}
    f444w = {flux = 'f_f444w', error = 'e_f444w'}
